paraglider-project/paraglider

- internal/cli/glide/rule/get/get.go
- internal/cli/glide/tag/list/list.go
- internal/cli/glide/tag/list/list_test.go
- internal/cli/glide/tag/tag.go
- pkg/client/client.go
- pkg/fake/orchestrator/rest/fake_orchestrator_rest_server.go
- pkg/orchestrator/orchestrator.go
- pkg/tag_service/tag_service.go
- pkg/tag_service/tagservicepb/tagservice.proto
Returns tag mappings 
Example : 
```
$ glide tag list
0). tag_name:"ibmvm1"  child_tags:"default.ibm.vm-1"
1). tag_name:"default.ibm.vm-1"  uri:"/resourcegroup/2d6e51c90e42424b8757d5a481e2450e/zone/us-east-1/instance/0757_7764d121-6465-4c70-a791-6fce774dd2fb"  ip:"10.0.0.9"
2). tag_name:"prod"  child_tags:"ibmvm1"
3). tag_name:"ibmvm2"  child_tags:"default.ibm.vm-2"
4). tag_name:"default.ibm.vm-2"  uri:"/resourcegroup/2d6e51c90e42424b8757d5a481e2450e/zone/us-east-1/instance/0757_006cd7db-1795-4b68-a380-1a6f023b8f65"  ip:"10.0.0.10"
```
> Add "glide tag list" support

- docs/source/index.rst
Otherwise there are two logos side by side on index.
> Revert title of index page to Welcome to Paraglider and remove logo

- pkg/azure/naming_test.go
- pkg/azure/resources_test.go
- pkg/gcp/resources_test.go
These tests were still running for integration and multicloud because there wasn't a space.
> Fix build tag typo

- .github/workflows/docs.yaml
Dependabot PRs need these permissions specified (https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions).
> [Infra] Specify permissions for docs workflows

- .devcontainer/devcontainer.json
- .github/workflows/build.yaml
Building off of #314. Would be nice to have one place for these versions (related to #187).
> [Infra] Update go 1.22 for dev container and GitHub Actions workflows

- Dockerfile
- build/build.mk
Docker images gets published in : 
https://github.com/orgs/paraglider-project/packages/container/package/paraglider
Next step would be add releases
Note: For now, I added config.yaml (as config argument for glided startup) which can be provided when executing the docker. 
`docker run -v /path/to/your/config.yaml:/config.yaml ghcr.io/paraglider-project/paraglider:latest`
However, we should see if we can simplify this further.
> Add support to build docker image

- .github/dependabot.yml
This will consolidate all Go updates into one PR, Python updates into one PR, etc. This will help declutter our PR page as well as reduce having to handle `go.sum` merge conflicts.
I configured it to only group for minor and patch version updates. Major version updates will still be created in their own PR.
> [Infra] Group dependabot updates by package ecosystem

- .github/workflows/build.yaml
We've been hitting some rate limits for arduino/setup-protoc step (example: https://github.com/paraglider-project/paraglider/actions/runs/9361388806/job/25768296034?pr=357). Specifying the token will give us access to higher limits.
> [Infra] Fix rate limit when using arduino/protoc

- .github/dependabot.yml
Better PR names for dependabot PRs when using groups
Before
```
Bump the all group across 1 directory with 9 updates
```
After
```
Bump the gomod-all group across 1 directory with 9 updates
```
> [Infra] Use package ecosystem name in dependabot group name

- .github/workflows/release.yml
Currently, a release is triggered upon PR merge. I realized it's because of `branch:main` in push, which doesn't filter out only tag pushes, but applies to all pushes (PR merge) to the main branch. 
I referred to bunch of other projects, which don't have this condition set. Hence, we should be ok with not having `branch:main` condition.
> Fix release trigger on PR Merge

- build/build.mk
linux/arm64 image release wasn't happening due to a build in build.mk, which uses local platform details and ignores the PLATFORMS flags passed down by release.yml. Additionally, fix unknown/unknown image tag bug.
> Fix linux/arm64 docker image release

- internal/cli/glide/rule/add/add.go
- internal/cli/glide/rule/add/add_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/fake/orchestrator/rest/fake_orchestrator_rest_server.go
- pkg/fake/tagservice/fake_tag_service.go
- pkg/orchestrator/orchestrator.go
- pkg/orchestrator/orchestrator_test.go
- pkg/paragliderpb/paraglider.proto
Enables users to apply rules (or delete rules) on tags. Before, users could only apply a rule on one resource at a time. Now, if a tag maps to many resources, this can be leveraged to apply a rule in one command to many resources.
Resolves #117
> Enable Permit List Rule Operations on Tags

- docs/source/developers/plugin-interface.rst
- docs/source/overview/api.rst
- docs/source/overview/quickstart.rst
- pkg/gcp/plugin_utils.go
- tools/examples/vm-configs/azure-vm-eastus.json
- tools/examples/vm-configs/azure-vm-westus.json
- tools/examples/vm-configs/gcp-vm.json
**Display name**
Our GitHub run numbers have become reached 4 digits, leading to display names that end up being > 30 characters (GCP imposed limit). For now, I truncated the prefix from "paraglider" to "glide". That should provide enough leeway for a while.
**Debian 10**
GCP integration test is failing due to [Debian 10 reaching its end of life](https://www.debian.org/News/2024/20240615). This doesn't affect Azure tests because those use Ubuntu 22.04.
I updated everything (i.e., GCP tests, GCP docs, and Azure docs) to use Ubuntu 22.04. Azure tests require Ubuntu 22.04 due to the network watcher extension, so I figured it's best if we make it clean and make everything use Ubuntu 22.04. I believe IBM already uses it as well.
> [GCP] Fix integration test bugs for display name and Debian 10

- pkg/azure/utils.go
- pkg/ibm/security_group.go
- pkg/ibm/subnets.go
- pkg/ibm/utils.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Moving the CIDR comparison functions from IBMs utils to the general utils folder, so it's available for all the clouds
> Refactor: Moving utils from ibm to general

- pkg/gcp/firewalls.go
- pkg/gcp/networks.go
- pkg/gcp/plugin.go
- pkg/gcp/plugin_integration_test.go
- pkg/gcp/plugin_test.go
- pkg/gcp/plugin_test_utils.go
- pkg/gcp/plugin_utils.go
- pkg/gcp/resources.go
- pkg/multicloud/multicloud_test.go
Changed the arguments of `RunPingConnectivityTest` such that users don't need to pass in `networkmanagement.networkmanagementpb.Endpoint`s. This is an exported function meant to be used in functional tests, so I presumed a new list of arguments with IP addresses and namespaces is better than using a specific GCP API struct.
Also fixes #158. Helps maintain consistency in how we export methods.
> [GCP] Refactor `RunPingConnectivityTest`

- docs/source/conf.py
Resolves #353. The view button will now also link to the file in GitHub rather than a raw dump.
@divega let me know if this is what you were thinking.
> [Docs] Add edit button

- pkg/azure/plugin.go
- pkg/azure/plugin_test.go
- pkg/azure/sdk_handler.go
- pkg/azure/sdk_handler_test.go
- pkg/azure/test_utils.go
- Currently, `GetUsedAddressSpaces` checks the vnet name prefix to determine if the vnet is managed by Paraglider. 
- Since we're supporting external vnet attachments, this PR updates the function to use the namespace tags attached to every Paraglider managed vnet, instead of just the name
- Fixes #404
> Update `GetUsedAddressSpaces` to use Paraglider vnet tags

- .github/workflows/build.yaml
- .github/workflows/functional-tests-approval.yaml
I updated our workflows to not run "Build and Test" and "Functional Test Approvals" for PRs that only change some files. The current reasoning behind each (listed under `paths-ignore` in the diff) is as follows.
- `.devcontainer/`: Not used in any of the build process, though this may change with #187
- `.githooks/`: same as above
- `docs/`: same as above (and already existed before this PR)
- `**.md`: excludes files such as README, CONTRIBUTING, CODE-OF-CONDUCT
- `**.rst`: not sure if this isn't covered anywhere that `docs/` doesn't cover since we don't use RST outside of docs but just as a safe measure
Resolves #259. @smcclure20 let me know your thoughts.
> [Infra] Ignore more paths to reduce extraneous builds

- pkg/azure/plugin.go
- pkg/azure/resources.go
- pkg/azure/sdk_handler.go
- pkg/azure/sdk_handler_test.go
- Create peering assumed the resource vnet name by prefixing the location with the paraglider prefix
- Updating to ensure that external vnets are supported
- Contributes to #170
> [Azure] Fix create peering

- pkg/orchestrator/orchestrator.go
- Checks that a resource tag does not already exist before creating or attaching a resource
- Closes #429
> Pre-creation/attachment check at orchestrator level

- README.md
- docs/source/index.rst
Added a Discord badge to our README for better accessibility and changed the one on the website so that the text "Discord" is searchable via cmd-f. @divega do you think this is sufficient enough for #375?
> [Docs] Improve Discord badge for better accessibility

- .github/workflows/functional-tests.yaml
This adds a manual trigger so that we can trigger the functional tests manually with the workflow file of a branch for the PR instead of pulling from main. No security concerns as only people with write access to the repo are allowed to manually trigger.
The caveat to this is that the checks shown at the bottom of the PR will still show failures from the auto triggered version. For any PRs that require changes to workflow files (which shouldn't be too many), we'll have to override the checks requirement and just merge as long as the manual triggered run passes tests.
> [Infra] Add manual trigger for functional tests

- .github/workflows/functional-tests.yaml
Turns out there already exists a separate dropdown to select which branch's workflow file to use.
> [Infra] Fix description of input for functional test manual trigger

- pkg/azure/sdk_handler.go
- Accounts for vnets not created by paraglider which may not the paraglider tag attached to it
- Fixes #496
> [Azure] Fix for namespace tag check for vnet

- pkg/gcp/resources.go
- pkg/gcp/resources_test.go
Returns 0 for non-Google services in `getNumberAddressSpacesRequired()`.
> Doesn't Allocate Address Space for Non-Google Services

- .github/workflows/functional-tests.yaml
- build/test.mk
- pkg/azure/plugin.go
- pkg/azure/plugin_integration_test.go
- pkg/azure/utils.go
- pkg/multicloud/multicloud_test.go
As mentioned in #525, we currently cannot create resources anywhere but westus2. While this is getting resolved, let's move all non-region-dependent instances of an arbitrary region to "westus2" so that it can work in the meantime.
Also, I added a change to put Azure integration tests on their own `make` command so that the pipeline can proceed without it (Authentication issues in #525), but we can run them locally for people who have access to an account.
> [Azure] Change all instances of "westus" to "westus2" for our current backend subscription

- pkg/orchestrator/orchestrator.go
- pkg/orchestrator/orchestrator_test.go
I found this bug by attempting to add a rule with the `--ping` flag to a tag rather than a resource (eg, `default.azure.vm1` instead of `azure vm1`). This results in two rules being sent in the payload to the orchestrator. While this is fine when applied to the function for resources, the one for tags only parsed one rule. 
I updated it to accept a list of rules (as the other APIs do)
> [Orchestrator] Allow multiple rules to be added at once when applying to a tag

- .devcontainer/devcontainer.json
- Updated dev container to use go version 1.23
- Updated dev container references from protoc and tmux-apt-get
> [Dev] Fixing dev container creation in json

- pkg/gcp/firewalls.go
- pkg/gcp/firewalls_test.go
- pkg/gcp/plugin.go
- pkg/gcp/plugin_test_utils.go
- pkg/gcp/resources.go
- pkg/gcp/resources_test.go
- Adds functions and tests to determine the compliance of existing GCP resources with paraglider for attachment
- Criteria for compliance:
> [GCP] [Draft] Compliance Tests of a Resource with Paraglider
